modLoader="javafml" 
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Noobanidus/Miniatures/issues"
license="https://github.com/Noobanidus/Miniatures/blob/master/LICENSE"
[[mods]] 
modId="miniatures"
version="${version}"
displayName="Miniatures"
displayURL="https://minecraft.curseforge.com/projects/miniatures"
credits="Miniatures"
authors="Noobanidus"
description='''
A port of Mini-Me entities from Miniatures 1.12.2.
'''
[[dependencies.miniatures]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.miniatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
