modLoader="javafml" 
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Noobanidus/Miniatures/issues"
license="https://github.com/Noobanidus/Miniatures/blob/master/LICENSE"
[[mods]] 
modId="miniatures"
version="${version}"
displayName="Miniatures"
displayURL="https://minecraft.curseforge.com/projects/miniatures"
credits="Miniatures"
authors="Noobanidus"
description='''
A port of Mini-Me entities from Miniatures 1.12.2.
'''
[[dependencies.miniatures]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.167,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.miniatures]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,)"
    ordering="NONE"
    side="BOTH"
